# Generated by Django 4.2.3 on 2023-07-04 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_date_remove_event_time_event_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 14, 22, 20, 392011, tzinfo=datetime.timezone.utc)),
        ),
    ]
