# Generated by Django 4.2.3 on 2023-07-04 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_duration_alter_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 14, 24, 58, 477245, tzinfo=datetime.timezone.utc)),
        ),
    ]
