# Generated by Django 4.2.3 on 2023-07-05 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_rename_event_registration_event_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='user_id',
            new_name='user',
        ),
    ]
