# Generated by Django 4.2.3 on 2023-07-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_rename_event_id_registration_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(to='events.category'),
        ),
    ]
